version: '3.8'
services:
  dev-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest
    networks:
      - RX-78-RH
    ports:
      - 5434:5432
networks:
  RX-78-RH:
